### ISSUE TITLE
crashed with other filter packages

### ISSUE THREAD

**Issue by riseno** [rcknr/nova-multiselect-filter#1]
Hi,

I installed this package and started to use, it works very well, however, it crashed other filter package like, [Date Filter](https://github.com/64robots/nova-date-filter)... 

I would love to use this package until you fixed this issue.

**Comment by SidiGi** [comment]
+1

**Comment by sidigi** [comment]
#3  decision

**Comment by skauk** [comment]
@riseno For a while, there was no support for custom filters in Nova so each custom filter package was a hack and conflicted with one another. Recently, the support was added and I have updated the package accordingly. Simply update with composer, no code changes required.
