### ISSUE TITLE
Reset Filters action doesn't clear the selections

### ISSUE THREAD

**Issue by asilverstein** [rcknr/nova-multiselect-filter#10]
When clicking the "RESET FILTERS" link that appears at the top of Nova's filter box, the Multiselect filters are not cleared from the UI. 

In the attached example images, my multiselect filter is named "Work Types", the first image shows the before state (before clicking "RESET FILTERS") and the second shows the after state (after clicking "RESET FILTERS").

![before](https://user-images.githubusercontent.com/440978/56163068-6f192800-5f9b-11e9-8bd3-90db25231515.png)
![after](https://user-images.githubusercontent.com/440978/56163074-70e2eb80-5f9b-11e9-8731-7302d2a80962.png)

**Comment by skauk** [comment]
If it's not the latest Nova version try downgrading.

**Comment by asilverstein** [comment]
Hi Sergii, I'm using Laravel 5.8.11. Do I need to use an older version of Laravel to work with nova-multiselect-filter?

**Comment by skauk** [comment]
@asilverstein Which Nova version do you use?

**Comment by asilverstein** [comment]
2.0

**Comment by skauk** [comment]
There were some changes in the way filters work in Nova 2.0.
