### ISSUE TITLE
Uncaught (in promise) - NavigationDuplicated

### ISSUE THREAD

**Issue by MohmmedAshraf** [rcknr/nova-multiselect-filter#12]
Hey, great work
After installing this package i got this error

![Screen Shot 2019-12-21 at 7 26 15 AM](https://user-images.githubusercontent.com/44909285/71303571-6ea31d80-23c3-11ea-8ecc-d06fa586ca64.png)

**Comment by skauk** [comment]
This doesn't appear to be caused by this package.
